import React from "react";

const LicenseContent = () => {
  const sections = [
    {
      title: "PARTIES TO THIS AGREEMENT",
      content: [
        'This License Agreement is entered into between BitWisdom Ai Network, LaLuz, LLC (hereinafter referred to as "BitWisdom Ai Network", "the Company", "we", "our", or "us") and the Licensee accepting the terms of this Agreement.',
      ],
    },

    {
      title: "DEFINITIONS",
      subsections: [
        {
          subtitle: "1.1 Software",
          content:
            "The software program(s) provided by BitWisdom Ai Network, including but not limited to, any updates, upgrades, and related documentation, which is designed to facilitate automated settlement of cryptocurrency transactions and enable residual payments based on transactions processed between merchants and their consumers.",
        },
        {
          subtitle: "1.2 Licensee",
          content:
            "The entity or individual who has acquired the right to access or use the Software, typically the customer running a server utilizing BitWisdom Ai Network's Software.",
        },
        {
          subtitle: "1.3 Merchants",
          content:
            "The individuals, businesses, or entities onboarded by the Licensee to access or use the Software in order to process cryptocurrency transactions with their consumers.",
        },
        {
          subtitle: "1.4 High Transaction Volume Merchants",
          content:
            "A customer or merchant that is also considered a qualifying BitWisdom Ai Network customer who expects or performs transaction volumes greater than $100,000 USD per month in cryptocurrency transactions, or any merchant whose transaction volume is deemed high risk by BitWisdom Ai Network.",
        },
        {
          subtitle: "1.5 Consumers",
          content:
            "The individuals or entities who access or use the Software through the Merchant's platform to engage in cryptocurrency transactions.",
        },
        {
          subtitle: "1.6 Residual Payments",
          content:
            "A 1.25% percentage of transaction fees earned by Licensee based on the cryptocurrency transactions facilitated by the Software, paid to Licensee for their role in onboarding and maintaining merchants.",
        },
        {
          subtitle: "1.7 BitWisdom Ai Network Residual",
          content:
            "BitWisdom Ai Network retains a 0.19444444444% residual fee on every transaction processed through the Software. This fee is in addition to the residual payments made to the Licensee.",
        },
        {
          subtitle: "1.8 Network Fees",
          content:
            "Additional network and blockchain transaction fees, which are typically 0.05% or less, but may fluctuate based on network conditions, market congestion, or other factors. These fees are unavoidable and are not within BitWisdom Ai Network's control.",
        },
        {
          subtitle: "1.9 Transaction Volume",
          content:
            "The aggregate total value of cryptocurrency transactions processed by the Software through the merchant's system, measured over a rolling 30-day or calendar month period.",
        },
        {
          subtitle: "1.10 Tiered Licensing Fees",
          content:
            "The monthly fees payable by Licensee to BitWisdom Ai Network, based on the transaction volume generated by the Merchants onboarded by the Licensee to access or use the Software, as outlined in Section 4.",
        },
      ],
    },

    {
      title: "LICENSE GRANT AND RESTRICTIONS",
      subsections: [
        {
          subtitle: "2.1 Grant of License",
          content:
            "Subject to the terms and conditions of this Agreement, BitWisdom Ai Network grants to Licensee a non-exclusive, non-transferable, and revocable license to access and use the Software solely for the purpose of facilitating cryptocurrency transactions between the Licensee's onboarded Merchants and their Consumers, including if the Licensee is a Merchant.",
        },
        {
          subtitle: "2.2 Residual Payment Structure",
          content:
            "Licensee will receive a residual payment equal to 1.25% of the transaction fees generated by transactions processed via the Software. These payments will be distributed to Licensee monthly, on the 28th day of each month, and are based on the volume of transactions processed by them or their onboarded Merchants during the preceding month.",
        },
        {
          subtitle: "2.3 BitWisdom Ai Network Residual",
          content:
            "BitWisdom Ai Network will retain a 0.19444444444% residual fee on every transaction processed by its Software. This fee is applied in addition to the 1.25% residual fee taken by Licensee from the transactions processed by their Merchants.",
        },
        {
          subtitle: "2.4 Network Fees",
          content:
            "Licensee acknowledges and agrees that in addition to the 1.25% residual fee charged to Merchants by Licensee, the total transaction fees charged to Merchants may include network fees, which typically total 0.05% but may fluctuate.",
        },
        {
          subtitle: "2.5 Fee Structure and Fluctuations",
          content:
            "The total fee charged to each Merchant for a transaction may therefore range from approximately 1.5% or less of the transaction amount but could occasionally exceed this amount if network conditions cause fees to increase.",
        },
        {
          subtitle: "2.6 Fee Adjustment Based on Transaction Volume",
          content:
            "Licensee shall pay tiered licensing fees based on transaction volume. Fees increase by $100 increments at each threshold up to a maximum monthly fee of $1,000.",
        },
      ],
    },

    {
      title: "DISCLAIMER OF WARRANTIES",
      subsections: [
        {
          subtitle: "3.1 No Warranty",
          content:
            'THE SOFTWARE IS PROVIDED "AS IS," AND BITWISDOM AI NETWORK MAKES NO WARRANTIES OF ANY KIND.',
        },
        {
          subtitle: "3.2 Cryptocurrency Risks",
          content:
            "Cryptocurrency involves substantial risk. BitWisdom Ai Network is not responsible for market loss, hacking, theft, or volatility issues.",
        },
      ],
    },

    {
      title: "LIMITATION OF LIABILITY",
      subsections: [
        {
          subtitle: "4.1 Limitation of Liability",
          content:
            "BITWISDOM AI NETWORK IS NOT LIABLE FOR INDIRECT OR CONSEQUENTIAL DAMAGES. Liability is capped at the total license fees paid in the past 12 months.",
        },
        {
          subtitle: "4.2 No Liability for Fluctuating Fees",
          content:
            "BitWisdom Ai Network is not responsible for fluctuations in network or blockchain fees.",
        },
        {
          subtitle: "4.3 No Liability for Misuse or Tampering",
          content:
            "Licensee is responsible for unauthorized use or system tampering by themselves or Merchants.",
        },
        {
          subtitle: "4.4 Loss of Funds",
          content:
            "BitWisdom Ai Network assumes no liability for cryptocurrency loss due to fraud, hacks, or blockchain issues.",
        },
        {
          subtitle: "4.5 Liability for High Transaction Volume Merchants",
          content:
            "High-volume merchants carry added risk. Licensee assumes full responsibility for compliance and transaction security.",
        },
      ],
    },

    {
      title: "INDEMNIFICATION",
      subsections: [
        {
          subtitle: "5.1 Indemnity",
          content:
            "Licensee agrees to indemnify and defend BitWisdom Ai Network against all claims arising from their use, misuse, or breach of this Agreement.",
        },
      ],
    },

    {
      title: "CUSTOMER OBLIGATIONS AND RESPONSIBILITIES",
      subsections: [
        {
          subtitle: "6.1 Security and Maintenance",
          content:
            "Licensee must maintain security of all systems, keys, and credentials.",
        },
        {
          subtitle: "6.2 Compliance with Laws",
          content:
            "Licensee must ensure compliance with all applicable laws, including merchants they onboard.",
        },
        {
          subtitle: "6.3 Merchant Onboarding and Oversight",
          content:
            "Licensee is responsible for all merchants they onboard and their activities.",
        },
      ],
    },

    {
      title: "TAMPERING AND PUNITIVE MEASURES",
      subsections: [
        {
          subtitle: "7.1 Tampering Detection",
          content:
            "Tampering triggers penalties, increased fees, or immediate termination.",
        },
        {
          subtitle: "7.2 Consequences of Tampering",
          content: "Tampering may lead to civil or criminal proceedings.",
        },
      ],
    },

    {
      title: "TERM AND TERMINATION",
      subsections: [
        {
          subtitle: "8.1 Term",
          content:
            "This Agreement remains active until terminated by either party.",
        },
        {
          subtitle: "8.2 Termination for Cause",
          content:
            "BitWisdom Ai Network may terminate access due to fraud or breach.",
        },
        {
          subtitle: "8.3 Effect of Termination",
          content: "All Software use must cease immediately upon termination.",
        },
      ],
    },

    {
      title: "HIGH TRANSACTION VOLUME CLAUSE",
      subsections: [
        {
          subtitle: "9.1 Transaction Monitoring and Reporting",
          content:
            "High-volume Licensees may be subject to AML/KYC monitoring.",
        },
        {
          subtitle: "9.2 Increased Scrutiny for High Transaction Volumes",
          content:
            "Enhanced due diligence may be required for high-risk merchants.",
        },
      ],
    },

    {
      title: "COMPLIANCE WITH AML/KYC REGULATIONS",
      subsections: [
        {
          subtitle: "10.1 AML/KYC Obligations",
          content:
            "Licensee must provide all AML/KYC information upon request.",
        },
        {
          subtitle: "10.2 High-Risk Merchant Policy",
          content: "High-risk merchants may be restricted or terminated.",
        },
        {
          subtitle: "10.3 Suspension for Non-Compliance",
          content:
            "Failure to satisfy AML/KYC requirements may result in suspension.",
        },
      ],
    },

    {
      title: "DISPUTE RESOLUTION",
      subsections: [
        {
          subtitle: "11.1 Arbitration",
          content:
            "All disputes shall be resolved via binding arbitration in Atlanta, Georgia.",
        },
        {
          subtitle: "11.2 Governing Law",
          content: "This Agreement is governed by Georgia law.",
        },
      ],
    },

    {
      title: "MISCELLANEOUS",
      subsections: [
        {
          subtitle: "12.1 Entire Agreement",
          content:
            "This Agreement is the full and complete understanding between the parties.",
        },
        {
          subtitle: "12.2 Amendments",
          content:
            "Modifications must be in writing and signed by both parties.",
        },
        {
          subtitle: "12.3 Severability",
          content:
            "Invalid provisions do not affect the remainder of the Agreement.",
        },
      ],
    },
  ];

  return (
    <section className="relative bg-[#0E0E0E] text-white py-12 px-4 overflow-hidden">
      <div className="absolute inset-0 opacity-5">
        <div className="absolute top-0 left-1/4 w-96 h-96 bg-cyan-400 rounded-full blur-3xl"></div>
        <div className="absolute bottom-0 right-1/4 w-96 h-96 bg-cyan-500 rounded-full blur-3xl"></div>
      </div>

      <div className="max-w-5xl mx-auto relative z-10">
        {/* INTRO */}
        <div className="mb-12">
          <p className="text-gray-300 text-lg">
            This Software License Agreement (the "Agreement") is made between{" "}
            <span className="font-semibold text-cyan-400">
              BitWisdom Ai Network, LaLuz, LLC
            </span>{" "}
            and the Licensee.
          </p>
          <p className="text-red-400 text-lg mt-4 font-semibold">
            By accessing or using the Software, the Licensee agrees to the terms
            of this Agreement.
          </p>
        </div>

        {/* ALL SECTIONS */}
        <div className="space-y-10">
          {sections.map((section, index) => (
            <div
              key={index}
              className="border border-cyan-400/30 rounded-xl p-6 hover:border-cyan-400 transition shadow-lg hover:shadow-cyan-400/20"
            >
              <h2 className="text-3xl font-bold mb-6 bg-gradient-to-b from-cyan-300 to-white bg-clip-text text-transparent">
                {index + 1}. {section.title}
              </h2>

              {/* If section has simple paragraph(s) */}
              {section.content && (
                <div className="space-y-4 pl-2">
                  {section.content.map((text, i) => (
                    <p
                      key={i}
                      className="text-gray-300 text-base leading-relaxed"
                    >
                      {text}
                    </p>
                  ))}
                </div>
              )}

              {/* If section has subsections */}
              {section.subsections?.length > 0 && (
                <div className="space-y-6">
                  {section.subsections.map((sub, sIndex) => (
                    <div key={sIndex} className="pl-3">
                      <h3 className="text-xl font-semibold text-cyan-300 mb-2">
                        {sub.subtitle}
                      </h3>
                      <p className="text-gray-300 text-base leading-relaxed">
                        {sub.content}
                      </p>
                    </div>
                  ))}
                </div>
              )}
            </div>
          ))}
        </div>

        {/* AGREEMENT ACKNOWLEDGEMENT */}
        <div className="mt-12 bg-cyan-400/10 border border-cyan-400/40 rounded-xl p-6">
          <h3 className="text-2xl font-bold text-cyan-400 mb-4">
            Agreement Acknowledgment
          </h3>
          <p className="text-gray-300 text-base leading-relaxed">
            By accessing or using the Software, you acknowledge that you have
            read, understood, and agree to be bound by this Software License
            Agreement. If you do not agree to these terms, you must not use the
            Software.
          </p>
        </div>
      </div>
    </section>
  );
};

export default LicenseContent;


